server.port=8090
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/espe_plus_db}
spring.datasource.username=${DB_USERNAME:espe.123}
spring.datasource.password=${DB_PASSWORD:paulo}
spring.jpa.hibernate.ddl-auto=update
langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY:demo}
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
